export enum STATUS {
  BACKLOG = 'BACKLOG',
  INPROGRESS = 'INPROGRESS',
  DONE = 'DONE',
}

export enum USER_ROLE {
  IT_USER = 'IT_USER',
  OTHER_USER = 'OTHER_USER',
}

export enum PRODUCT {
  WEBSITE = 'WEBSITE',
  MOBILE_APP = 'MOBILE_APP',
  SUBSCRIPTION = 'SUBSCRIPTION',
  GENERAL = 'GENERAL',
  OTHER = 'OTHER',
}
